// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5J5b82yGnxfAjFSvdvvI1j45s0TKrYCk',
    appId: '1:307299357997:android:511a8f1f4c55a56549efa4',
    messagingSenderId: '307299357997',
    projectId: 'aa-schedule-manager',
    storageBucket: 'aa-schedule-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaYopo04P5iv5nY7wTvK8Ysvkp4aC3a_U',
    appId: '1:307299357997:ios:67c08f2bc7f92ec049efa4',
    messagingSenderId: '307299357997',
    projectId: 'aa-schedule-manager',
    storageBucket: 'aa-schedule-manager.appspot.com',
    iosBundleId: 'com.aasm.scheduleManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaYopo04P5iv5nY7wTvK8Ysvkp4aC3a_U',
    appId: '1:307299357997:ios:6dbe0ef4e8fe1adb49efa4',
    messagingSenderId: '307299357997',
    projectId: 'aa-schedule-manager',
    storageBucket: 'aa-schedule-manager.appspot.com',
    iosBundleId: 'com.aasm.scheduleManager.RunnerTests',
  );
}
